#!/bin/bash
# =============================================================================
# CreditWise PostgreSQL Setup Script
# =============================================================================
# This script helps set up the PostgreSQL database for CreditWise.
# 
# Prerequisites:
#   - PostgreSQL installed (brew install postgresql on macOS)
#   - PostgreSQL service running
#
# Usage:
#   chmod +x setup_postgres.sh
#   ./setup_postgres.sh
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  CreditWise PostgreSQL Setup${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}❌ PostgreSQL is not installed!${NC}"
    echo ""
    echo "Please install PostgreSQL first:"
    echo "  macOS: brew install postgresql@15"
    echo "  Ubuntu: sudo apt install postgresql postgresql-contrib"
    echo ""
    exit 1
fi

echo -e "${GREEN}✓ PostgreSQL is installed${NC}"

# Check if PostgreSQL is running
if ! pg_isready &> /dev/null; then
    echo -e "${YELLOW}⚠ PostgreSQL is not running. Attempting to start...${NC}"
    
    # Try to start PostgreSQL (macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew services start postgresql@15 || brew services start postgresql
    else
        sudo systemctl start postgresql
    fi
    
    sleep 2
    
    if ! pg_isready &> /dev/null; then
        echo -e "${RED}❌ Could not start PostgreSQL${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}✓ PostgreSQL is running${NC}"

# Database configuration
DB_NAME="creditwise"
DB_USER="creditwise_user"
DB_PASSWORD="creditwise_secure_password"

echo ""
echo -e "${YELLOW}Creating database and user...${NC}"

# Create database and user
psql -U postgres << EOF
-- Create user if not exists
DO
\$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_USER}') THEN
      CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
   END IF;
END
\$\$;

-- Create database if not exists
SELECT 'CREATE DATABASE ${DB_NAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};
EOF

echo -e "${GREEN}✓ Database '${DB_NAME}' created${NC}"
echo -e "${GREEN}✓ User '${DB_USER}' created${NC}"

# Create .env file
echo ""
echo -e "${YELLOW}Creating .env file...${NC}"

cat > .env << EOF
# CreditWise Backend Configuration
# ================================
# Generated by setup_postgres.sh

# Database
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}

# JWT Configuration (Change in production!)
SECRET_KEY=$(openssl rand -hex 32)
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# Application
DEBUG=True
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:5173

# ML Model Path
MODEL_PATH=../notebooks/best_tft_model.pt
EOF

echo -e "${GREEN}✓ .env file created${NC}"

# Install Python dependencies
echo ""
echo -e "${YELLOW}Installing Python dependencies...${NC}"

if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${RED}❌ requirements.txt not found${NC}"
fi

# Initialize database tables
echo ""
echo -e "${YELLOW}Initializing database tables...${NC}"

python init_db.py

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Database Connection:"
echo "  Host: localhost"
echo "  Port: 5432"
echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo ""
echo "Next Steps:"
echo "  1. Start the API server:"
echo "     cd backend && python run.py"
echo ""
echo "  2. Open API documentation:"
echo "     http://localhost:8000/docs"
echo ""
echo "  3. Start the frontend:"
echo "     cd 'Design CreditWise Platform' && npm run dev"
echo ""

